# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        main:
            entity: { class: Blog\UserBundle\Entity\User, property: username }
    encoders:
          Blog\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12


    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      login:
        pattern: ^/login$
        anonymous: ~

      main:
        pattern: ^/
        form_login:
            login_path: login
            check_path: login_check
        anonymous: true
        provider: main

        logout:
            path: /logout
            target: /

        remember_me:
          secret: '%secret%'

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }